// client/src/app/components/masquer-text/masquer-text.component.ts
import { Component, OnInit, Input } from '@angular/core';

interface MasquerChar {
  char: string;
  class: string;
  flip: boolean;
  fontSize: string;
}

const getRandomInt = (max: number) => {
  return Math.floor(Math.random() * max);
};

@Component({
  selector: 'app-masquer-text',
  templateUrl: './masquer-text.component.html',
  styleUrls: ['./masquer-text.component.css'],
})
export class MasquerTextComponent implements OnInit {
  @Input() text: string = '';
  @Input() flipIndices: number[] = [];
  @Input() leftFontSize: number = 48;
  @Input() fontSizeStep: number = 0;
  @Input() rotateAngle: string = "0deg";
  @Input() rotateOrigin: string = "50% 50%";
  @Input() hoverWiggle: boolean = false;
  @Input() hoverInvert: boolean = false;
  @Input() hoverBackdrop: boolean = false;
  public charArray: MasquerChar[] = [];

  constructor() {}

  ngOnInit(): void {
    this.charArray = this.text.split('').map((c, idx) => {
      return {
        char: c,
        class: "masquer-char-span" + getRandomInt(10),
        flip: this.flipIndices.includes(idx),
        fontSize: this.leftFontSize + idx*this.fontSizeStep + "px"
      }
    });
  }

  getRotationString() {
    return `rotate(${this.rotateAngle})`;
  }
}

<div
  class="masquer-text-container"
  [ngClass]="{
    hoverwiggle: hoverWiggle,
    hoverinvert: hoverInvert,
    hoverbackdrop: hoverBackdrop
  }"
  [ngStyle]="{
    transform: getRotationString(),
    'transform-origin': rotateOrigin
  }"
>
  <div class="backdrop">
    <span
      *ngFor="let masquerChar of charArray"
      [ngClass]="{ flip: masquerChar.flip }"
      [ngStyle]="{
        'font-size': masquerChar.fontSize
      }"
      class="back {{ masquerChar.class }}"
    >
      {{ masquerChar.char }}
    </span>
  </div>
  <span
    *ngFor="let masquerChar of charArray"
    [ngClass]="{ flip: masquerChar.flip }"
    [ngStyle]="{
      'font-size': masquerChar.fontSize
    }"
    class="fore {{ masquerChar.class }}"
  >
    {{ masquerChar.char }}
  </span>
</div>

// components/MasquerText.tsx
import React from "react";
import styles from "../styles/MasquerText.module.css";
import { getRandomInt } from "../lib/utils";

const VARIATIONS = [
  styles.variation0,
  styles.variation1,
  styles.variation2,
  styles.variation3,
  styles.variation4,
  styles.variation5,
  styles.variation6,
  styles.variation7,
  styles.variation8,
  styles.variation9,
];

interface MasquerChar {
  char: string;
  class: string;
  flip: boolean;
  fontSize: number;
}

type Props = {
  text: string;
  flipIndices: number[];
  leftFontSize: number;
  fontStepSize: number;
  transform: string;
  transformOrigin: string;
  hoverInvert: boolean;
  hoverBackdrop: boolean;
};

function MasquerText(props: Props) {
  const {
    text,
    flipIndices,
    leftFontSize,
    fontStepSize,
    transform,
    transformOrigin,
    hoverInvert,
    hoverBackdrop,
  } = props;

  const chars: MasquerChar[] = text.split("").map((c, i) => ({
    char: c,
    class: VARIATIONS[getRandomInt(0, 10)],
    flip: flipIndices.includes(i),
    fontSize: leftFontSize + i * fontStepSize,
  }));

  return (
    <div
      className={`
        ${styles.container}
        ${hoverInvert ? styles.hoverinvert : ""}
        ${hoverBackdrop ? styles.hoverbackdrop : ""}
      `}
      style={{
        transform: transform,
        transformOrigin: transformOrigin,
      }}
    >
      <div className="absolute">
        {chars.map((char, i) => (
          <span
            key={i}
            className={`
              inline-block
              ${styles.back} 
              ${char.class} 
              ${char.flip ? styles.flip : ""}
            `}
            style={{
              fontSize: char.fontSize,
              WebkitTextStrokeWidth: Math.floor(char.fontSize / 4),
            }}
          >
            {char.char}
          </span>
        ))}
      </div>
      {chars.map((char, i) => (
        <span
          key={i}
          className={`
            inline-block
            ${styles.fore} 
            ${char.class} 
            ${char.flip ? styles.flip : ""}
          `}
          style={{ fontSize: char.fontSize }}
        >
          {char.char}
        </span>
      ))}
    </div>
  );
}

export default MasquerText;
