// components/Sidebar.tsx
import React from "react";
import styles from "../styles/Sidebar.module.css";
import MasquerText from "./MasquerText";
import { FaTheaterMasks } from "react-icons/fa";
import { useRouter } from "next/router";
import { signOut } from "../services/auth";

function Sidebar() {
  const router = useRouter();

  const handleLogout = () => {
    return signOut().then(() => {
      router.push("/");
    });
  };

  return (
    <div className={styles.anchor}>
      <div className={styles.container}>
        <FaTheaterMasks size="10rem" color="#ffffff" />

        <div className={styles.optionsContainer}>
          <div
            className={`${styles.option} ${styles.home}`}
            onClick={() => router.push("/home")}
          >
            <MasquerText
              text="HoMe"
              flipIndices={[]}
              leftFontSize={81}
              fontStepSize={-15}
              transform="rotate(2deg)"
              transformOrigin="right 100%"
              hoverInvert={true}
            />
          </div>
          <div
            className={`${styles.option} ${styles.chats}`}
            onClick={() => router.push("/chats")}
          >
            <MasquerText
              text="CHats"
              flipIndices={[2]}
              leftFontSize={36}
              fontStepSize={18}
              transform="rotate(-10deg)"
              transformOrigin="left 100%"
              hoverInvert={true}
            />
          </div>
          <div
            className={`${styles.option} ${styles.profile}`}
            onClick={() => router.push("/profile")}
          >
            <MasquerText
              text="ProFile"
              flipIndices={[0, 3]}
              leftFontSize={56}
              fontStepSize={-4}
              transform="rotate(-20deg)"
              transformOrigin="right 100%"
              hoverInvert={true}
            />
          </div>
          <div
            className={`${styles.option} ${styles.logout}`}
            onClick={handleLogout}
          >
            <MasquerText
              text="LogOut"
              flipIndices={[3]}
              leftFontSize={32}
              fontStepSize={10}
              transform="rotate(15deg)"
              transformOrigin="left 100%"
              hoverInvert={true}
            />
          </div>
        </div>
      </div>
    </div>
  );
}

export default Sidebar;

// client/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { faTheaterMasks } from '@fortawesome/free-solid-svg-icons';
import { UserService } from 'src/app/services/user.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css'],
})
export class SidebarComponent implements OnInit {
  maskIcon = faTheaterMasks;

  constructor(private userSerivce: UserService, private router: Router) {}

  ngOnInit(): void {}

  handleSignOut() {
    this.userSerivce.signout().subscribe(() => {
      this.router.navigate(['/']);
    });
  }
}

<div class="sidebar">
  <fa-icon [icon]="maskIcon" class="sidebar-icon fa-10x"></fa-icon>

  <div class="option-container home">
    <app-masquer-text
      text="HoMe"
      [flipIndices]="[2]"
      [leftFontSize]="32"
      [fontSizeStep]="15"
      rotateAngle="-40deg"
      rotateOrigin="left 100%"
      [hoverInvert]="true"
      [hoverBackdrop]="true"
      class="sidebar-option home"
      (click)="navigateToHome()"
    ></app-masquer-text>
  </div>

  <div class="option-container chats">
    <app-masquer-text
      text="CHats"
      [flipIndices]="[2]"
      [leftFontSize]="32"
      [fontSizeStep]="15"
      rotateAngle="-30deg"
      rotateOrigin="left 50%"
      [hoverInvert]="true"
      [hoverBackdrop]="true"
      class="sidebar-option chats"
      (click)="navigateToChats()"
    ></app-masquer-text>
  </div>

  <div class="option-container profile">
    <app-masquer-text
      text="ProFile"
      [flipIndices]="[0, 3]"
      [leftFontSize]="32"
      [fontSizeStep]="8"
      rotateAngle="-10deg"
      rotateOrigin="left 50%"
      [hoverInvert]="true"
      [hoverBackdrop]="true"
      class="sidebar-option profile"
    ></app-masquer-text>
  </div>

  <div class="option-container logout">
    <app-masquer-text
      text="LogOut"
      [flipIndices]="[3]"
      [leftFontSize]="32"
      [fontSizeStep]="10"
      rotateAngle="5deg"
      rotateOrigin="left 0%"
      [hoverInvert]="true"
      [hoverBackdrop]="true"
      class="sidebar-option logout"
      (click)="handleSignOut()"
    ></app-masquer-text>
  </div>
</div>
